embedder:
  model: BAAI/bge-m3
  device: cpu

llm:
  provider: ollama
  model: qwen3:8b
  endpoint: http://localhost:11434
  max_tokens: 768
  temperature: 0.2

retriever:
  collection_name: law_kb_m3
  top_k: 6
  chunk_size: 800
  chunk_overlap: 120
  use_reranker: true
  reranker_model: BAAI/bge-reranker-large

vectorstore:
  provider: chroma
  path: vectorstore

server:
  host: 0.0.0.0
  port: 8000

prompts:
  system: prompts/system.txt

retriever:
  collection_name: cases_kb_m3

